# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Badminton_My_Home_Trainer(object):
    def setupUi(self, Badminton_My_Home_Trainer):
        Badminton_My_Home_Trainer.setObjectName("Badminton_My_Home_Trainer")
        Badminton_My_Home_Trainer.resize(1920, 1080)
        Badminton_My_Home_Trainer.setStyleSheet("border-image: url(:/assets/screen.png);")
        self.centralwidget = QtWidgets.QWidget(Badminton_My_Home_Trainer)
        self.centralwidget.setObjectName("centralwidget")
        self.play = QtWidgets.QPushButton(self.centralwidget)
        self.play.setGeometry(QtCore.QRect(1550, 730, 180, 180))
        self.play.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.play.setStyleSheet("border-image: url(:/assets/playbutton.png);")
        self.play.setText("")
        self.play.setObjectName("play")
        Badminton_My_Home_Trainer.setCentralWidget(self.centralwidget)

        self.retranslateUi(Badminton_My_Home_Trainer)
        QtCore.QMetaObject.connectSlotsByName(Badminton_My_Home_Trainer)

    def retranslateUi(self, Badminton_My_Home_Trainer):
        _translate = QtCore.QCoreApplication.translate
        Badminton_My_Home_Trainer.setWindowTitle(_translate("Badminton_My_Home_Trainer", "Badminton_My_Home_Trainer"))
import picture_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Badminton_My_Home_Trainer = QtWidgets.QMainWindow()
    ui = Ui_Badminton_My_Home_Trainer()
    ui.setupUi(Badminton_My_Home_Trainer)
    Badminton_My_Home_Trainer.show()
    sys.exit(app.exec_())
