# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI6.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UI_high_clear(object):
    def setupUi(self, UI_high_clear):
        UI_high_clear.setObjectName("UI_high_clear")
        UI_high_clear.resize(1920, 1080)
        UI_high_clear.setStyleSheet("background-color: rgb(132, 163, 132);")
        self.step2_Button = QtWidgets.QPushButton(UI_high_clear)
        self.step2_Button.setGeometry(QtCore.QRect(510, 400, 420, 420))
        self.step2_Button.setStyleSheet("border-image: url(:/assets/high_clear_step2.png);")
        self.step2_Button.setText("")
        self.step2_Button.setObjectName("step2_Button")
        self.step3_Button = QtWidgets.QPushButton(UI_high_clear)
        self.step3_Button.setGeometry(QtCore.QRect(990, 400, 420, 420))
        self.step3_Button.setStyleSheet("border-image: url(:/assets/high_clear_step3.png);")
        self.step3_Button.setText("")
        self.step3_Button.setObjectName("step3_Button")
        self.step4_Button = QtWidgets.QPushButton(UI_high_clear)
        self.step4_Button.setGeometry(QtCore.QRect(1470, 400, 420, 420))
        self.step4_Button.setStyleSheet("border-image: url(:/assets/high_clear_step4.png);")
        self.step4_Button.setText("")
        self.step4_Button.setObjectName("step4_Button")
        self.backButton = QtWidgets.QPushButton(UI_high_clear)
        self.backButton.setGeometry(QtCore.QRect(1650, 30, 250, 140))
        self.backButton.setStyleSheet("border-image: url(:/assets/back_button.png);")
        self.backButton.setText("")
        self.backButton.setObjectName("backButton")
        self.step1_Button = QtWidgets.QPushButton(UI_high_clear)
        self.step1_Button.setGeometry(QtCore.QRect(30, 400, 420, 420))
        self.step1_Button.setStyleSheet("border-image: url(:/assets/high_clear_step1.png);")
        self.step1_Button.setText("")
        self.step1_Button.setObjectName("step1_Button")

        self.retranslateUi(UI_high_clear)
        QtCore.QMetaObject.connectSlotsByName(UI_high_clear)

    def retranslateUi(self, UI_high_clear):
        _translate = QtCore.QCoreApplication.translate
        UI_high_clear.setWindowTitle(_translate("UI_high_clear", "Dialog"))
import picture_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    UI_high_clear = QtWidgets.QDialog()
    ui = Ui_UI_high_clear()
    ui.setupUi(UI_high_clear)
    UI_high_clear.show()
    sys.exit(app.exec_())
