# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI7.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UI_smash(object):
    def setupUi(self, UI_smash):
        UI_smash.setObjectName("UI_smash")
        UI_smash.resize(1920, 1080)
        UI_smash.setStyleSheet("background-color: rgb(132, 163, 132);")
        self.step1_Button = QtWidgets.QPushButton(UI_smash)
        self.step1_Button.setGeometry(QtCore.QRect(180, 400, 420, 420))
        self.step1_Button.setStyleSheet("border-image: url(:/assets/smash_step1.png);")
        self.step1_Button.setText("")
        self.step1_Button.setObjectName("step1_Button")
        self.step2_Button = QtWidgets.QPushButton(UI_smash)
        self.step2_Button.setGeometry(QtCore.QRect(720, 400, 420, 420))
        self.step2_Button.setStyleSheet("border-image: url(:/assets/smash_step2.png);")
        self.step2_Button.setText("")
        self.step2_Button.setObjectName("step2_Button")
        self.step3_Button = QtWidgets.QPushButton(UI_smash)
        self.step3_Button.setGeometry(QtCore.QRect(1260, 400, 420, 420))
        self.step3_Button.setStyleSheet("border-image: url(:/assets/smash_step3.png);")
        self.step3_Button.setText("")
        self.step3_Button.setObjectName("step3_Button")
        self.backButton = QtWidgets.QPushButton(UI_smash)
        self.backButton.setGeometry(QtCore.QRect(1650, 30, 250, 140))
        self.backButton.setStyleSheet("border-image: url(:/assets/back_button.png);")
        self.backButton.setText("")
        self.backButton.setObjectName("backButton")

        self.retranslateUi(UI_smash)
        QtCore.QMetaObject.connectSlotsByName(UI_smash)

    def retranslateUi(self, UI_smash):
        _translate = QtCore.QCoreApplication.translate
        UI_smash.setWindowTitle(_translate("UI_smash", "Dialog"))
import picture_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    UI_smash = QtWidgets.QDialog()
    ui = Ui_UI_smash()
    ui.setupUi(UI_smash)
    UI_smash.show()
    sys.exit(app.exec_())
